contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #practicetwo channel"
    url: https://nfcore.slack.com/channels/practicetwo
    about: Discussion about the nf-core/practicetwo pipeline
